server {
  listen 80;
  server_name mussoconnect.ml www.mussoconnect.ml;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name mussoconnect.ml www.mussoconnect.ml;

  # Certbot gérera les lignes ssl_certificate

  location / {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /api {
    proxy_pass http://localhost:4000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
